# Generated by Django 5.1.1 on 2024-10-14 15:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_mesa", models.IntegerField()),
                ("lugares", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Prato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_prato", models.IntegerField()),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("categoria", models.CharField(max_length=255)),
                ("valor", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Restaurante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("localizacao", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PratoPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "prato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.prato"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="prato",
            name="restaurante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pratos",
                to="core.restaurante",
            ),
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome_cliente", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Em Aberto", "Em Aberto"),
                            ("Preparando", "Preparando"),
                            ("Pedido Pronto", "Pedido Pronto"),
                            ("Fechado", "Fechado"),
                        ],
                        default="Em Aberto",
                        max_length=255,
                    ),
                ),
                ("horario_pedido", models.DateTimeField(auto_now_add=True)),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.mesa"
                    ),
                ),
                (
                    "pratos",
                    models.ManyToManyField(
                        blank=True, related_name="pedidos", to="core.pratopedido"
                    ),
                ),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="core.restaurante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=255)),
                ("visualizada", models.BooleanField(default=False)),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to="core.restaurante",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mesa",
            name="restaurante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mesas",
                to="core.restaurante",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="prato",
            unique_together={("restaurante", "numero_prato")},
        ),
        migrations.AlterUniqueTogether(
            name="mesa",
            unique_together={("restaurante", "numero_mesa")},
        ),
    ]
