# Generated by Django 5.1.1 on 2024-09-05 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "numero_mesa",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("lugares", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Prato",
            fields=[
                (
                    "numero_prato",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome_cliente", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("Em Aberto", "Em Aberto"), ("Fechado", "Fechado")],
                        default="Em Aberto",
                        max_length=255,
                    ),
                ),
                ("horario_pedido", models.DateTimeField(auto_now_add=True)),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.mesa"
                    ),
                ),
                ("pratos", models.ManyToManyField(to="core.prato")),
            ],
        ),
    ]
