# Generated by Django 5.1.1 on 2024-10-25 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=500, null=True)),
                ("cpf_cnpj", models.CharField(blank=True, max_length=30, null=True)),
                ("ddd", models.CharField(blank=True, max_length=4, null=True)),
                ("telefone", models.CharField(blank=True, max_length=500, null=True)),
                ("rg", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("cep", models.CharField(blank=True, max_length=20, null=True)),
                ("endereco", models.CharField(blank=True, max_length=500, null=True)),
                ("numero", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("bairro", models.CharField(blank=True, max_length=500, null=True)),
                ("cidade", models.CharField(blank=True, max_length=500, null=True)),
                ("uf", models.CharField(blank=True, max_length=2, null=True)),
                ("referencia", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "observacoes",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Pessoas",
                        to="core.restaurante",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="cliente",
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "pessoa_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.pessoa",
                    ),
                ),
                ("pode_acessar_pdv", models.BooleanField(default=False)),
                ("pode_acessar_garcom", models.BooleanField(default=False)),
                ("pode_acessar_cozinha", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funcionario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("core.pessoa",),
        ),
        migrations.AddField(
            model_name="pedido",
            name="pessoa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.pessoa",
            ),
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
    ]
