# Generated by Django 5.1.1 on 2024-09-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_mesa_numero_mesa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="pratos",
            field=models.ManyToManyField(blank=True, null=True, to="core.prato"),
        ),
    ]
