# Generated by Django 5.1.1 on 2024-10-25 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_funcionario_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caixa",
            name="operador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="caixas",
                to="core.funcionario",
            ),
        ),
    ]
