# Generated by Django 5.1.1 on 2024-09-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_pedido_pratos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="pratos",
            field=models.ManyToManyField(
                blank=True, related_name="pedidos", to="core.prato"
            ),
        ),
    ]
