# Generated by Django 5.1.1 on 2024-09-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_pedido_pratos"),
    ]

    operations = [
        migrations.AddField(
            model_name="prato",
            name="valor",
            field=models.IntegerField(null=True),
        ),
    ]
