# Generated by Django 5.1.1 on 2024-09-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_prato_valor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prato",
            name="valor",
            field=models.IntegerField(),
        ),
    ]
