# Generated by Django 5.1.1 on 2024-10-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_caixa_saldo_final_alter_caixa_saldo_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="valor_pago",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
