# Generated by Django 5.1.1 on 2024-09-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_prato_valor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("Em Aberto", "Em Aberto"),
                    ("Preparando", "Preparando"),
                    ("Fechado", "Fechado"),
                ],
                default="Em Aberto",
                max_length=255,
            ),
        ),
    ]
