# Generated by Django 5.1.1 on 2024-10-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_pedido_valor_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="valor_pago",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
