# Generated by Django 5.1.1 on 2024-10-26 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_pedido_valor_pago"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metodopagamento",
            name="pedido",
        ),
        migrations.AddField(
            model_name="pedido",
            name="pagamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pedidos",
                to="core.metodopagamento",
            ),
        ),
    ]
