# Generated by Django 5.1.1 on 2024-09-18 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_pedido_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PratoPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "prato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.prato"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="pedido",
            name="pratos",
            field=models.ManyToManyField(
                blank=True, related_name="pedidos", to="core.pratopedido"
            ),
        ),
    ]
