# Generated by Django 5.1.1 on 2024-10-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_metodopagamento_pedido_pedido_pagamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="pagamento",
        ),
        migrations.AddField(
            model_name="pedido",
            name="pagamento",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="pedidos", to="core.metodopagamento"
            ),
        ),
    ]
