# Generated by Django 5.1.1 on 2024-10-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_pedido_pagamento_pedido_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="pagamento",
            field=models.ManyToManyField(
                blank=True, related_name="pedidos", to="core.metodopagamento"
            ),
        ),
    ]
