# Generated by Django 5.1.1 on 2024-10-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_pedido_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="desconto",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="subtotal",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="troco",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
