# Generated by Django 5.1.1 on 2024-10-27 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_pedido_desconto_pedido_subtotal_pedido_troco"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sangria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.FloatField()),
                ("descricao", models.CharField(max_length=255)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("suprimentos", "suprimentos"),
                            ("outros", "outros"),
                            ("manutencao", "manutencao"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "caixa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sangrias",
                        to="core.caixa",
                    ),
                ),
            ],
        ),
    ]
