# Generated by Django 5.1.1 on 2024-10-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_sangria"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sangria",
        ),
    ]
