# Generated by Django 5.1.1 on 2024-10-27 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_delete_sangria"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acrescimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.IntegerField()),
                ("descricao", models.CharField(max_length=255)),
                (
                    "categoria",
                    models.CharField(
                        choices=[("suprimentos", "suprimentos"), ("outros", "outros")],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "caixa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acrescimos",
                        to="core.caixa",
                    ),
                ),
            ],
        ),
    ]
