# Generated by Django 5.1.1 on 2024-10-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_acrescimo"),
    ]

    operations = [
        migrations.AddField(
            model_name="mesa",
            name="ocupada",
            field=models.BooleanField(default=False),
        ),
    ]
