# Generated by Django 5.1.1 on 2024-10-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_mesa_ocupada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mesa",
            name="ocupada",
        ),
        migrations.RemoveField(
            model_name="mesa",
            name="reservada",
        ),
        migrations.AddField(
            model_name="mesa",
            name="status",
            field=models.CharField(
                choices=[
                    ("Disponível", "Disponível"),
                    ("Reservada", "Reservada"),
                    ("Ocupada", "Ocupada"),
                ],
                default="Disponível",
                max_length=20,
            ),
        ),
    ]
