# Generated by Django 5.1.1 on 2024-10-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_mesa_ocupada_remove_mesa_reservada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="codigo",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
