# Generated by Django 5.1.1 on 2024-10-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_pedido_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("Em Aberto", "Em Aberto"),
                    ("Preparando", "Preparando"),
                    ("Pedido Pronto", "Pedido Pronto"),
                    ("Fechado", "Fechado"),
                    ("Em Rota", "Em Rota"),
                    ("Entregue", "Entregue"),
                    ("Cancelado", "Cancelado"),
                ],
                default="Em Aberto",
                max_length=255,
            ),
        ),
    ]
