# Generated by Django 5.1.1 on 2024-11-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_pedido_data_pedido"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=255)),
                ("expires_in", models.IntegerField()),
                ("token_type", models.CharField(default="Bearer", max_length=50)),
                ("scope", models.CharField(blank=True, max_length=255)),
                ("refresh_token", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField(editable=False)),
            ],
        ),
    ]
