# Generated by Django 5.1.1 on 2024-11-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_authenticationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="observacao",
            field=models.CharField(default="", max_length=255),
        ),
    ]
