# Generated by Django 5.1.1 on 2024-11-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_pedido_valor_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="valor_pago",
            field=models.FloatField(default=0, null=True),
        ),
    ]
