# Generated by Django 5.1.1 on 2024-11-12 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_pedido_valor_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="prato",
            name="mostrar_cardapio",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="prato",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pratos",
                to="core.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="prato",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prato",
            name="numero_prato",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
